-- Find the size of all tables in a given database
SELECT TABLE_NAME, TABLE_ROWS, DATA_LENGTH, INDEX_LENGTH,
       (DATA_LENGTH + INDEX_LENGTH) "Size in bytes"
  FROM INFORMATION_SCHEMA.TABLES
 WHERE TABLE_SCHEMA = 'CONFERENCE_REVIEW';

SELECT SUM(TOTAL_SIZE)
  FROM (SELECT (DATA_LENGTH + INDEX_LENGTH) AS TOTAL_SIZE
          FROM INFORMATION_SCHEMA.TABLES
	 WHERE TABLE_SCHEMA = 'CONFERENCE_REVIEW') SIZE_STATS;

-- Enable the profiler
SET PROFILING=1;

-- Display profiling data for all queries
SHOW PROFILES;

-- Display profiling data for a specific query
SHOW PROFILE FOR QUERY 41;

-- Show all table indexes
SELECT DISTINCT TABLE_NAME, INDEX_NAME
  FROM INFORMATION_SCHEMA.STATISTICS
 WHERE TABLE_SCHEMA = 'CONFERENCE_REVIEW';
